import Head from 'next/head'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import { useSnapshot } from 'valtio'

import { IoMdMoon, IoMdSunny } from 'react-icons/io'

import state from '../store'
import { CustomButton, CustomLink, Navbar, Footer } from '../components'
import {
    headContainerAnimation,
    headContentAnimation,
    headTextAnimation,
    slideAnimation
} from '../config/motion'

import { tile1, tile2, tile3, logoblack, logowhite, selldark, sellwhite, buydark, buywhite } from '../assets'

export default function Home() {
    const snap = useSnapshot(state)
    return (
        <AnimatePresence>
            <Head>
            <title>FAQ | AITropy</title>
            <meta name="description" content="Explore the world of AI-generated texts, images, and prompts with AITropy. Buy, sell, and discover a lot of products for and created by GPT, DALL-E, STABLE DIFFUSION, and MIDJOURNEY tools. Start today! | AITropy" />
            <meta name="keywords" content="marketplace, ai-generated products, prompts, images, texts, gpt, dall-e, stable diffusion, midjourney, AI, artificial intelligence, buy, sell, community, no-fees" />
            <meta property="og:title" content="FAQ | AITropy" />
            <meta property="og:description" content="Explore the world of AI-generated texts, images, and prompts with AITropy. Buy, sell, and discover a lot of products for and created by GPT, DALL-E, STABLE DIFFUSION, and MIDJOURNEY tools. Start today! | AITropy" />
            <meta property="og:url" content={`${process.env.NEXT_PUBLIC_AITROPY_URL}`} />
            <meta name="twitter:title" content="FAQ | AITropy" />
            <meta name="twitter:description" content="Explore the world of AI-generated texts, images, and prompts with AITropy. Buy, sell, and discover a lot of products for and created by GPT, DALL-E, STABLE DIFFUSION, and MIDJOURNEY tools. Start today! | AITropy" />
            <link rel="icon" href="/favicon.png" />
            </Head>
            <motion.div className='flex flex-wrap fixed z-[10000] gap-1 bottom-4 right-4 bg-[#04E762]  text-white font-bold py-2 px-4 rounded-full'>
                <a onClick={() => (state.themeDark = true) && (state.themeLight = false)} className='cursor-pointer hover:text-gray-500 transition-all ease-in-out'><IoMdMoon size={25} /></a>
                <a onClick={() => (state.themeLight = true) && (state.themeDark = false)} className='cursor-pointer hover:text-gray-500 transition-all ease-in-out'><IoMdSunny size={25} /></a>
            </motion.div>
            {snap.themeLight && (
                <motion.div className='max-w-[3840px] m-auto'>
                        <motion.div className='max-w-[3840px] m-auto'>
                            <Navbar />
                        </motion.div>
                        <motion.div className='max-w-[1920px] m-auto'>
                            <motion.div {...headTextAnimation} className='mt-8 md:min-h-screen'>
                                <h2 className='2xl:text-[3rem] text-[1.5rem] font-black text-black text-center'>FAQ</h2>
                                <motion.div {...headContentAnimation} className='flex flex-col gap-5 mt-4'>
                                <p className='md:max-w-[80%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>If you can't find the answer to your question here, get in contact with us <a className='font-medium' href="mailto:aitropy.io@gmail.com">via email</a>.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>What is AITropy?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>AITropy is a marketplace for buying and selling images, texts and prompts generated by or created for GPT, DALL·E, Stable Diffusion, Midjourney and other AI tools. Prompts are text commands that are fed into complex AI models to get a desired output.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>Is there any cost for using AITropy?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>No. AITropy is free to use for everyone. We neither charge any additional fee on your sales. You'll receive the price you set for your products minus the PayPal fee for online transactions.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>How do I get paid?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>We use PayPal to handle all transactions on AITropy. You'll receive all the funds of your sales on your vinculated PayPal account. Before setting up your first product for sale, you'll be asked to integrate your PayPal account.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>How long does it take for my product to be approved?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>We aim to review and approve your product within 6-12 hours.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>Do I still own my product if I list it?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>Yes. You retain all rights to your product, and are welcome to remove it from AITropy at any point.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-black text-center'>Do you offer rewards for bug encountering?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-gray-600 text-base'>We offer small awards for confidentially disclosing bugs discovered through AITropy. To disclose a bug, send us <a className='font-medium' href="mailto:aitropy.io@gmail.com">an email</a> clearly explaining how the bug is carried out. If we deem the bug severe enough, we will reward you.</p>
                                </motion.div>
                            </motion.div>
                        </motion.div>
                        <motion.div className='max-w-[3840px] m-auto mt-10'>
                            <Footer />
                        </motion.div>
                </motion.div>
            )}
            {snap.themeDark && (
                <motion.div className='max-w-[3840px] m-auto bg-gray-900 md:min-h-screen'>
                        <motion.div className='max-w-[3840px] m-auto'>
                            <Navbar />
                        </motion.div>
                        <motion.div className='max-w-[1920px] m-auto'>
                        <motion.div {...headTextAnimation} className='mt-8 md:min-h-screen'>
                                <h2 className='2xl:text-[3rem] text-[1.5rem] font-black text-white text-center'>FAQ</h2>
                                <motion.div {...headContentAnimation} className='flex flex-col gap-5 mt-4'>
                                <p className='md:max-w-[80%] max-w-[90%] text-center m-auto font-normal text-white text-base'>If you can't find the answer to your question here, get in contact with us <a className='font-medium' href="mailto:aitropy.io@gmail.com">via email</a>.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>What is AITropy?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>AITropy is a marketplace for buying and selling images, texts and prompts generated by or created for GPT, DALL·E, Stable Diffusion, Midjourney and other AI tools. Prompts are text commands that are fed into complex AI models to get a desired output.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>Is there any cost for using AITropy?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>No. AITropy is free to use for everyone. We neither charge any additional fee on your sales. You'll receive the price you set for your products minus the PayPal fee for online transactions.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>How do I get paid?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>We use PayPal to handle all transactions on AITropy. You'll receive all the funds of your sales on your vinculated PayPal account. Before setting up your first product for sale, you'll be asked to integrate your PayPal account.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>How long does it take for my product to be approved?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>We aim to review and approve your product within 6-12 hours.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>Do I still own my product if I list it?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>Yes. You retain all rights to your product, and are welcome to remove it from AITropy at any point.</p>
                                <h2 className='2xl:text-[1.75rem] text-[1.1rem] font-black text-white text-center'>Do you offer rewards for bug encountering?</h2>
                                <p className='md:max-w-[60%] max-w-[90%] text-center m-auto font-normal text-white text-base'>We offer small awards for confidentially disclosing bugs discovered through AITropy. To disclose a bug, send us <a className='font-medium' href="mailto:aitropy.io@gmail.com">an email</a> clearly explaining how the bug is carried out. If we deem the bug severe enough, we will reward you.</p>
                                </motion.div>
                            </motion.div>
                        </motion.div>
                        <motion.div className='max-w-[3840px] m-auto mt-10'>
                            <Footer />
                        </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    )
}